// examples/vue/src/components/Editor.vue
<script setup lang="ts">
import { reactive, useTemplateRef } from "vue";
import { YamlEditor, DiffView } from "@visual-yaml/vue";
import { useYamlDocument } from "../composables/use-yaml-document";
import type { Sample } from "../composables/use-yaml-document";

type ViewMode = "tree" | "raw" | "diff";

const VIEW_MODES: { id: ViewMode; label: string }[] = [
  { id: "tree", label: "Tree" },
  { id: "raw", label: "Raw" },
  { id: "diff", label: "Diff" },
];

const samples: Sample[] = [
  {
    name: "package.json",
    filename: "package.json",
    data: {
      name: "my-app",
      version: "1.0.0",
      private: true,
      scripts: {
        dev: "vite dev",
        build: "vite build",
        preview: "vite preview",
      },
      dependencies: {
        vue: "^3.5.0",
        vite: "^6.0.0",
      },
      devDependencies: {
        "@vitejs/plugin-vue": "^5.0.0",
        typescript: "^5.6.0",
      },
      engines: { node: ">=18" },
    },
  },
  {
    name: "tsconfig.json",
    filename: "tsconfig.json",
    data: {
      compilerOptions: {
        target: "ES2020",
        lib: ["DOM", "DOM.Iterable", "ES2020"],
        module: "ESNext",
        moduleResolution: "bundler",
        jsx: "preserve",
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        forceConsistentCasingInFileNames: true,
        resolveJsonModule: true,
        isolatedModules: true,
        noEmit: true,
        baseUrl: ".",
        paths: { "@/*": ["./*"] },
      },
      include: ["src/**/*.ts", "src/**/*.vue"],
      exclude: ["node_modules", "dist"],
    },
  },
  {
    name: "json-render spec",
    filename: "spec.json",
    data: {
      root: "card_1",
      elements: {
        card_1: {
          type: "Card",
          props: { title: "User Profile" },
          children: ["stack_1"],
        },
        stack_1: {
          type: "Stack",
          props: { gap: 16 },
          children: ["avatar_1", "heading_1", "text_1"],
        },
        avatar_1: {
          type: "Avatar",
          props: { src: "https://example.com/avatar.jpg", alt: "Jane Doe" },
        },
        heading_1: { type: "Heading", props: { level: 2, text: "Jane Doe" } },
        text_1: {
          type: "Text",
          props: { text: "Senior Software Engineer" },
        },
      },
    },
  },
];

const {
  yamlValue, originalJson, filename, activeSample, schema,
  rawText, rawError, parseError,
  loadJson, loadSample, handleJsonChange, handleRawChange,
} = useYamlDocument(samples[0]);

const ui = reactive({
  viewMode: "tree" as ViewMode,
  sidebarOpen: true,
  isDragOver: false,
  pasteDialogOpen: false,
  pasteText: "",
  settingsOpen: false,
  treeShowValues: false,
  treeShowCounts: false,
  editorShowDescriptions: false,
  editorShowCounts: false,
});

const dropZone = useTemplateRef<HTMLDivElement>("dropZone");
const fileInput = useTemplateRef<HTMLInputElement>("fileInput");

async function handlePaste() {
  try {
    const text = await navigator.clipboard.readText();
    loadJson(text, "pasted.json");
  } catch {
    ui.pasteText = "";
    ui.pasteDialogOpen = true;
  }
}

function handlePasteSubmit() {
  if (ui.pasteText.trim()) {
    loadJson(ui.pasteText, "pasted.json");
  }
  ui.pasteDialogOpen = false;
  ui.pasteText = "";
}

function handleDownload() {
  const text = JSON.stringify(yamlValue.value, null, 2);
  const blob = new Blob([text], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename.value;
  a.click();
  URL.revokeObjectURL(url);
}

async function handleCopyJson() {
  try {
    await navigator.clipboard.writeText(JSON.stringify(yamlValue.value, null, 2));
  } catch {}
}

function handleFileInput(e: Event) {
  const file = (e.target as HTMLInputElement).files?.[0];
  if (file) {
    const reader = new FileReader();
    reader.onload = () => {
      if (typeof reader.result === "string") loadJson(reader.result, file.name);
    };
    reader.readAsText(file);
  }
  (e.target as HTMLInputElement).value = "";
}

// Drag-and-drop file onto page
function handleDragOver(e: DragEvent) {
  if (!e.dataTransfer?.types.includes("Files")) return;
  ui.isDragOver = true;
}

function handleDragLeave(e: DragEvent) {
  if (!e.dataTransfer?.types.includes("Files")) return;
  if (e.relatedTarget === null || !dropZone.value?.contains(e.relatedTarget as Node)) {
    ui.isDragOver = false;
  }
}

function handleFileDrop(e: DragEvent) {
  ui.isDragOver = false;
  const file = e.dataTransfer?.files[0];
  if (file) {
    const reader = new FileReader();
    reader.onload = () => {
      if (typeof reader.result === "string") loadJson(reader.result, file.name);
    };
    reader.readAsText(file);
  }
}

</script>

<template>
  <div ref="dropZone" class="flex flex-col h-full bg-[var(--bg)] text-[var(--text)]" @dragover.prevent="handleDragOver" @dragleave="handleDragLeave" @drop.prevent="handleFileDrop">
    <!-- Drop overlay -->
    <div v-if="ui.isDragOver" class="absolute inset-0 z-50 flex items-center justify-center bg-[var(--drop-overlay-bg)] pointer-events-none">
      <div class="border-2 border-dashed border-[#007acc] rounded-lg px-12 py-8 text-base font-mono text-[#ccc]">Drop JSON file here</div>
    </div>

    <!-- Parse error -->
    <div v-if="parseError" class="error-banner">
      <span>{{ parseError }}</span>
      <button class="bg-transparent border-none text-inherit cursor-pointer text-4 leading-none p-0 px-0.5" @click="() => (parseError = null)">
        <div class="i-lucide-x" />
      </button>
    </div>

    <!-- Toolbar -->
    <div class="flex items-center gap-1.5 px-3 h-11 bg-[var(--toolbar-bg)] border-b border-[var(--toolbar-border)] shrink-0">
      <button
        class="toolbar-btn"
        :title="ui.sidebarOpen ? 'Hide sidebar' : 'Show sidebar'"
        @click="() => (ui.sidebarOpen = !ui.sidebarOpen)"
      >
        <div :class="ui.sidebarOpen ? 'i-lucide-panel-left-close' : 'i-lucide-panel-left'" />
      </button>

      <select
        class="bg-[var(--select-bg)] border border-[var(--border)] rounded text-[var(--text)] text-xs font-inherit py-0.75 px-1.5 cursor-pointer outline-none"
        :value="activeSample"
        @change="(e) => loadSample((e.target as HTMLSelectElement).value, samples)"
      >
        <option v-for="s in samples" :key="s.filename" :value="s.filename">
          {{ s.name }}
        </option>
      </select>

      <div class="w-px h-5 bg-[var(--border)] mx-0.5" />

      <input
        ref="fileInput"
        type="file"
        accept=".json,.jsonc,.json5"
        class="hidden"
        @change="handleFileInput"
      />
      <button class="toolbar-btn" title="Open file" @click="() => fileInput?.click()">
        <div class="i-lucide-folder-open" />
      </button>
      <button class="toolbar-btn" title="Paste JSON" @click="handlePaste">
        <div class="i-lucide-clipboard-paste" />
      </button>
      <button class="toolbar-btn" title="Download" @click="handleDownload">
        <div class="i-lucide-download" />
      </button>
      <button class="toolbar-btn" title="Copy JSON" @click="handleCopyJson">
        <div class="i-lucide-copy" />
      </button>

      <div class="flex-1" />

      <!-- View mode toggle -->
      <div class="flex items-center border border-[var(--border)] rounded overflow-hidden">
        <button
          v-for="m in VIEW_MODES"
          :key="m.id"
          class="view-toggle-btn"
          :class="{ active: ui.viewMode === m.id }"
          @click="() => (ui.viewMode = m.id)"
        >
          {{ m.label }}
        </button>
      </div>

      <button
        class="toolbar-btn"
        title="Settings"
        @click="() => (ui.settingsOpen = true)"
      >
        <div class="i-lucide-settings" />
      </button>
    </div>

    <!-- Editor area -->
    <div class="flex-1 min-h-0 relative">
      <!-- Raw view -->
      <div v-if="ui.viewMode === 'raw'" class="flex flex-col h-full bg-[var(--bg)]">
        <div v-if="rawError" class="error-banner justify-start!">
          {{ rawError }}
        </div>
        <textarea
          class="flex-1 w-full bg-transparent text-[var(--text)] font-mono text-13px p-4 resize-none outline-none border-none leading-relaxed"
          :value="rawText"
          spellcheck="false"
          @input="(e) => handleRawChange((e.target as HTMLTextAreaElement).value)"
        />
      </div>

      <!-- Diff view -->
      <DiffView
        v-else-if="ui.viewMode === 'diff'"
        :original-json="originalJson"
        :current-json="yamlValue"
        :style="{ height: '100%' }"
      />

      <!-- Tree/form editor -->
      <YamlEditor
        v-else
        :value="yamlValue"
        :schema="schema"
        :tree-show-values="ui.treeShowValues"
        :tree-show-counts="ui.treeShowCounts"
        :editor-show-descriptions="ui.editorShowDescriptions"
        :editor-show-counts="ui.editorShowCounts"
        :sidebar-open="ui.sidebarOpen"
        :style="{ height: '100%' }"
        @change="handleJsonChange"
      />
    </div>

    <!-- Paste dialog -->
    <div
      v-if="ui.pasteDialogOpen"
      class="fixed inset-0 z-100 bg-black/40 flex items-center justify-center"
      @click.self="() => (ui.pasteDialogOpen = false)"
    >
      <div class="settings-panel min-w-100">
        <h3>Paste JSON</h3>
        <textarea
          :value="ui.pasteText"
          placeholder="Paste your JSON here..."
          spellcheck="false"
          class="w-full min-h-45 bg-[var(--input-bg)] border border-[var(--input-border)] rounded text-[var(--text)] font-mono text-13px p-2 resize-y outline-none box-border"
          @input="(e) => (ui.pasteText = (e.target as HTMLTextAreaElement).value)"
        />
        <div class="flex gap-2 mt-3 justify-end">
          <button class="settings-close w-auto! py-1.5 px-4" @click="() => (ui.pasteDialogOpen = false)">
            Cancel
          </button>
          <button
            class="settings-close w-auto! py-1.5 px-4 bg-[#007acc]! text-white! border-[#007acc]!"
            @click="handlePasteSubmit"
          >
            Load
          </button>
        </div>
      </div>
    </div>

    <!-- Settings panel -->
    <div
      v-if="ui.settingsOpen"
      class="fixed inset-0 z-100 bg-black/40 flex items-center justify-center"
      @click.self="() => (ui.settingsOpen = false)"
    >
      <div class="settings-panel">
        <h3>Settings</h3>
        <div class="mb-4">
          <h4>Tree</h4>
          <div class="settings-row">
            <span>Values</span>
            <label class="toggle">
              <input
                type="checkbox"
                v-model="ui.treeShowValues"
              />
              <span class="toggle-slider" />
            </label>
          </div>
          <div class="settings-row">
            <span>Property counts</span>
            <label class="toggle">
              <input
                type="checkbox"
                v-model="ui.treeShowCounts"
              />
              <span class="toggle-slider" />
            </label>
          </div>
        </div>
        <div class="mb-4">
          <h4>Editor</h4>
          <div class="settings-row">
            <span>Descriptions</span>
            <label class="toggle">
              <input
                type="checkbox"
                v-model="ui.editorShowDescriptions"
              />
              <span class="toggle-slider" />
            </label>
          </div>
          <div class="settings-row">
            <span>Property counts</span>
            <label class="toggle">
              <input
                type="checkbox"
                v-model="ui.editorShowCounts"
              />
              <span class="toggle-slider" />
            </label>
          </div>
        </div>
        <button class="settings-close" @click="() => (ui.settingsOpen = false)">
          Close
        </button>
      </div>
    </div>
  </div>
</template>

// apps/web/src/app/editor.tsx
"use client";

import { useState, useCallback, useEffect, useRef } from "react";
import type { YamlValue, YamlSchema } from "@visual-yaml/core";
import { resolveSchema } from "@visual-yaml/core";
import { YamlEditor } from "@visual-yaml/react";
import { Button } from "@/components/ui/button";
import {
  Select,
  SelectTrigger,
  SelectContent,
  SelectItem,
} from "@/components/ui/select";
import { ToggleGroup, ToggleGroupItem } from "@/components/ui/toggle-group";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
  DialogFooter,
  DialogClose,
} from "@/components/ui/dialog";
import { Switch } from "@/components/ui/switch";
import { Label } from "@/components/ui/label";
import {
  FolderOpen,
  ClipboardPaste,
  Download,
  Copy,
  Settings,
  PanelLeftClose,
  PanelLeft,
  X,
} from "lucide-react";

type ViewMode = "tree" | "raw";

const VIEW_MODES: { id: ViewMode; label: string }[] = [
  { id: "tree", label: "Tree" },
  { id: "raw", label: "Raw" },
];

const samples: { name: string; filename: string; data: YamlValue }[] = [
  {
    name: "package.json",
    filename: "package.json",
    data: {
      name: "my-app",
      version: "1.0.0",
      private: true,
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
        lint: "next lint",
      },
      dependencies: {
        next: "^15.0.0",
        react: "^19.0.0",
        "react-dom": "^19.0.0",
      },
      devDependencies: {
        "@types/react": "^19.0.0",
        typescript: "^5.6.0",
        eslint: "^9.0.0",
      },
      engines: { node: ">=18" },
    },
  },
  {
    name: "OpenAPI spec",
    filename: "openapi.json",
    data: {
      openapi: "3.1.0",
      info: {
        title: "Tasks API",
        version: "1.0.0",
        description: "A simple task management API",
        contact: { name: "API Support", email: "support@example.com" },
        license: { name: "MIT", url: "https://opensource.org/licenses/MIT" },
      },
      servers: [
        {
          url: "https://api.example.com/v1",
          description: "Production",
        },
        {
          url: "https://staging-api.example.com/v1",
          description: "Staging",
        },
      ],
      paths: {
        "/tasks": {
          get: {
            summary: "List tasks",
            operationId: "listTasks",
            tags: ["tasks"],
            parameters: [
              {
                name: "status",
                in: "query",
                required: false,
                schema: { type: "string", enum: ["open", "closed", "all"] },
              },
              {
                name: "limit",
                in: "query",
                required: false,
                schema: { type: "integer", default: 20, maximum: 100 },
              },
            ],
            responses: {
              "200": {
                description: "A list of tasks",
                content: {
                  "application/json": {
                    schema: {
                      type: "array",
                      items: { $ref: "#/components/schemas/Task" },
                    },
                  },
                },
              },
            },
          },
          post: {
            summary: "Create a task",
            operationId: "createTask",
            tags: ["tasks"],
            requestBody: {
              required: true,
              content: {
                "application/json": {
                  schema: { $ref: "#/components/schemas/TaskInput" },
                },
              },
            },
            responses: {
              "201": {
                description: "Task created",
                content: {
                  "application/json": {
                    schema: { $ref: "#/components/schemas/Task" },
                  },
                },
              },
              "422": { description: "Validation error" },
            },
          },
        },
        "/tasks/{taskId}": {
          get: {
            summary: "Get a task",
            operationId: "getTask",
            tags: ["tasks"],
            parameters: [
              {
                name: "taskId",
                in: "path",
                required: true,
                schema: { type: "string", format: "uuid" },
              },
            ],
            responses: {
              "200": {
                description: "Task details",
                content: {
                  "application/json": {
                    schema: { $ref: "#/components/schemas/Task" },
                  },
                },
              },
              "404": { description: "Task not found" },
            },
          },
          patch: {
            summary: "Update a task",
            operationId: "updateTask",
            tags: ["tasks"],
            parameters: [
              {
                name: "taskId",
                in: "path",
                required: true,
                schema: { type: "string", format: "uuid" },
              },
            ],
            requestBody: {
              required: true,
              content: {
                "application/json": {
                  schema: { $ref: "#/components/schemas/TaskInput" },
                },
              },
            },
            responses: {
              "200": {
                description: "Task updated",
                content: {
                  "application/json": {
                    schema: { $ref: "#/components/schemas/Task" },
                  },
                },
              },
            },
          },
          delete: {
            summary: "Delete a task",
            operationId: "deleteTask",
            tags: ["tasks"],
            parameters: [
              {
                name: "taskId",
                in: "path",
                required: true,
                schema: { type: "string", format: "uuid" },
              },
            ],
            responses: {
              "204": { description: "Task deleted" },
            },
          },
        },
      },
      components: {
        schemas: {
          Task: {
            type: "object",
            required: ["id", "title", "status", "createdAt"],
            properties: {
              id: { type: "string", format: "uuid" },
              title: { type: "string", example: "Write docs" },
              description: { type: "string", nullable: true },
              status: {
                type: "string",
                enum: ["open", "in_progress", "closed"],
              },
              priority: { type: "string", enum: ["low", "medium", "high"] },
              assignee: { type: "string", nullable: true },
              tags: { type: "array", items: { type: "string" } },
              createdAt: { type: "string", format: "date-time" },
              updatedAt: { type: "string", format: "date-time" },
            },
          },
          TaskInput: {
            type: "object",
            required: ["title"],
            properties: {
              title: { type: "string", minLength: 1, maxLength: 200 },
              description: { type: "string", nullable: true },
              status: {
                type: "string",
                enum: ["open", "in_progress", "closed"],
              },
              priority: { type: "string", enum: ["low", "medium", "high"] },
              assignee: { type: "string", nullable: true },
              tags: { type: "array", items: { type: "string" } },
            },
          },
        },
        securitySchemes: {
          bearerAuth: {
            type: "http",
            scheme: "bearer",
            bearerFormat: "JWT",
          },
        },
      },
      security: [{ bearerAuth: [] }],
    },
  },
  {
    name: "json-render spec",
    filename: "spec.json",
    data: {
      root: "card_1",
      elements: {
        card_1: {
          type: "Card",
          props: { title: "User Profile" },
          children: ["stack_1"],
        },
        stack_1: {
          type: "Stack",
          props: { gap: 16 },
          children: ["avatar_1", "heading_1", "text_1", "button_group"],
        },
        avatar_1: {
          type: "Avatar",
          props: {
            src: "https://example.com/avatar.jpg",
            alt: "Jane Doe",
            size: "lg",
          },
        },
        heading_1: { type: "Heading", props: { level: 2, text: "Jane Doe" } },
        text_1: {
          type: "Text",
          props: { text: "Senior Software Engineer at Acme Corp." },
        },
        button_group: {
          type: "ButtonGroup",
          children: ["btn_edit", "btn_share"],
        },
        btn_edit: {
          type: "Button",
          props: { label: "Edit Profile", variant: "default" },
        },
        btn_share: {
          type: "Button",
          props: { label: "Share", variant: "outline" },
        },
      },
    },
  },
  {
    name: "json-render (nested)",
    filename: "dashboard.json",
    data: {
      type: "Stack",
      props: { direction: "vertical", gap: "lg" },
      state: {
        activeTab: "overview",
        notifications: true,
        darkMode: false,
        count: 42,
      },
      children: [
        {
          type: "Stack",
          props: { direction: "horizontal", gap: "md", align: "center" },
          children: [
            { type: "Heading", props: { text: "Dashboard", level: "h1" } },
            {
              type: "Text",
              props: { text: "Manage your workspace", variant: "muted" },
            },
          ],
        },
        {
          type: "Tabs",
          props: {
            tabs: [
              { label: "Overview", value: "overview" },
              { label: "Settings", value: "settings" },
            ],
            value: { $bindState: "/activeTab" },
          },
        },
        {
          type: "Stack",
          props: { direction: "vertical", gap: "md" },
          visible: [{ $state: "/activeTab", eq: "overview" }],
          children: [
            {
              type: "Grid",
              props: { columns: 3, gap: "md" },
              children: [
                {
                  type: "Card",
                  props: { title: "Active Users" },
                  children: [
                    {
                      type: "Metric",
                      props: { label: "Users", value: 1284, change: "+12%" },
                    },
                  ],
                },
                {
                  type: "Card",
                  props: { title: "Revenue" },
                  children: [
                    {
                      type: "Metric",
                      props: {
                        label: "Revenue",
                        value: "$48,200",
                        change: "+8.2%",
                      },
                    },
                  ],
                },
                {
                  type: "Card",
                  props: { title: "Orders" },
                  children: [
                    {
                      type: "Metric",
                      props: {
                        label: "Orders",
                        value: { $state: "/count" },
                        change: "-3%",
                      },
                    },
                  ],
                },
              ],
            },
            {
              type: "Card",
              props: { title: "Recent Activity" },
              children: [
                {
                  type: "Stack",
                  props: { direction: "vertical", gap: "sm" },
                  children: [
                    {
                      type: "Text",
                      props: {
                        text: "Alice deployed v2.4.0 to production",
                      },
                    },
                    {
                      type: "Text",
                      props: {
                        text: "Bob opened PR #312: Fix auth redirect",
                      },
                    },
                    {
                      type: "Text",
                      props: { text: "Carol added 3 new test cases" },
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          type: "Card",
          props: { title: "Preferences" },
          visible: [{ $state: "/activeTab", eq: "settings" }],
          children: [
            {
              type: "Stack",
              props: { direction: "vertical", gap: "md" },
              children: [
                {
                  type: "Switch",
                  props: {
                    label: "Email notifications",
                    checked: { $bindState: "/notifications" },
                  },
                },
                {
                  type: "Switch",
                  props: {
                    label: "Dark mode",
                    checked: { $bindState: "/darkMode" },
                  },
                },
                {
                  type: "Button",
                  props: { label: "Save preferences", variant: "primary" },
                  on: { press: { action: "confetti" } },
                },
              ],
            },
          ],
        },
      ],
    },
  },
];

export function Editor({
  defaultSidebarOpen,
}: {
  defaultSidebarOpen: boolean;
}) {
  const [activeSample, setActiveSample] = useState(samples[0].filename);
  const [yamlValue, setYamlValue] = useState<YamlValue>(samples[0].data);
  const [viewMode, setViewMode] = useState<ViewMode>("tree");
  const [schema, setSchema] = useState<YamlSchema | null>(null);
  const [filename, setFilename] = useState(samples[0].filename);
  const [isDragOver, setIsDragOver] = useState(false);
  const [sidebarOpen, setSidebarOpen] = useState(defaultSidebarOpen);
  const [treeShowValues, setTreeShowValues] = useState(false);
  const [treeShowCounts, setTreeShowCounts] = useState(false);
  const [editorShowDescriptions, setEditorShowDescriptions] = useState(false);
  const [editorShowCounts, setEditorShowCounts] = useState(false);
  const [rawText, setRawText] = useState(
    JSON.stringify(samples[0].data, null, 2),
  );
  const [rawError, setRawError] = useState<string | null>(null);
  const [parseError, setParseError] = useState<string | null>(null);
  const [pasteDialogOpen, setPasteDialogOpen] = useState(false);
  const [pasteText, setPasteText] = useState("");
  const dropRef = useRef<HTMLDivElement>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const skipRawSync = useRef(false);

  useEffect(() => {
    let cancelled = false;
    resolveSchema(yamlValue, filename).then((s) => {
      if (!cancelled) setSchema(s);
    });
    return () => {
      cancelled = true;
    };
  }, [filename]);

  useEffect(() => {
    if (skipRawSync.current) {
      skipRawSync.current = false;
      return;
    }
    setRawText(JSON.stringify(yamlValue, null, 2));
  }, [yamlValue]);

  const loadJson = useCallback((text: string, fname: string) => {
    try {
      const parsed = JSON.parse(text);
      setYamlValue(parsed);
      setFilename(fname);
      setActiveSample(fname);
      setSchema(null);
      setRawError(null);
      setParseError(null);
    } catch {
      setParseError("Invalid JSON");
    }
  }, []);

  const handleSampleChange = useCallback((fname: string) => {
    const sample = samples.find((s) => s.filename === fname);
    if (sample) {
      setActiveSample(fname);
      setFilename(fname);
      setYamlValue(sample.data);
      setSchema(null);
      setRawError(null);
    }
  }, []);

  const handlePaste = useCallback(async () => {
    try {
      const text = await navigator.clipboard.readText();
      loadJson(text, "pasted.json");
    } catch {
      setPasteText("");
      setPasteDialogOpen(true);
    }
  }, [loadJson]);

  const handlePasteSubmit = useCallback(() => {
    if (pasteText.trim()) {
      loadJson(pasteText, "pasted.json");
    }
    setPasteDialogOpen(false);
    setPasteText("");
  }, [pasteText, loadJson]);

  const handleDownload = useCallback(() => {
    const text = JSON.stringify(yamlValue, null, 2);
    const blob = new Blob([text], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  }, [yamlValue, filename]);

  const handleCopyJson = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(JSON.stringify(yamlValue, null, 2));
    } catch {
      // clipboard access may be denied
    }
  }, [yamlValue]);

  const handleRawChange = useCallback((newText: string) => {
    setRawText(newText);
    try {
      const parsed = JSON.parse(newText);
      setRawError(null);
      skipRawSync.current = true;
      setYamlValue(parsed);
    } catch (e) {
      setRawError(e instanceof Error ? e.message : "Invalid JSON");
    }
  }, []);

  useEffect(() => {
    const el = dropRef.current;
    if (!el) return;
    function handleDragOver(e: DragEvent) {
      if (!e.dataTransfer?.types.includes("Files")) return;
      e.preventDefault();
      setIsDragOver(true);
    }
    function handleDragLeave(e: DragEvent) {
      if (!e.dataTransfer?.types.includes("Files")) return;
      e.preventDefault();
      if (e.relatedTarget === null || !el!.contains(e.relatedTarget as Node))
        setIsDragOver(false);
    }
    function handleDrop(e: DragEvent) {
      if (!e.dataTransfer?.types.includes("Files")) return;
      e.preventDefault();
      setIsDragOver(false);
      const file = e.dataTransfer?.files[0];
      if (file) {
        const reader = new FileReader();
        reader.onload = () => {
          if (typeof reader.result === "string")
            loadJson(reader.result, file.name);
        };
        reader.readAsText(file);
      }
    }
    el.addEventListener("dragover", handleDragOver);
    el.addEventListener("dragleave", handleDragLeave);
    el.addEventListener("drop", handleDrop);
    return () => {
      el.removeEventListener("dragover", handleDragOver);
      el.removeEventListener("dragleave", handleDragLeave);
      el.removeEventListener("drop", handleDrop);
    };
  }, [loadJson]);

  return (
    <div
      ref={dropRef}
      className="flex flex-col h-[calc(100vh-3.5rem)] relative"
    >
      {isDragOver && (
        <div className="absolute inset-0 z-50 flex items-center justify-center bg-black/60 pointer-events-none">
          <div className="border-2 border-dashed border-primary rounded-lg p-8">
            <span className="text-foreground text-lg font-mono">
              Drop JSON file here
            </span>
          </div>
        </div>
      )}

      {parseError && (
        <div className="flex items-center justify-between px-3 py-1.5 text-xs bg-red-100 text-red-700 dark:bg-red-950 dark:text-red-400 border-b border-border shrink-0">
          <span>{parseError}</span>
          <button
            onClick={() => setParseError(null)}
            aria-label="Dismiss error"
          >
            <X className="h-3 w-3" />
          </button>
        </div>
      )}

      {/* Toolbar */}
      <div className="flex items-center gap-2 px-4 h-11 border-b border-border bg-background shrink-0">
        <Button
          variant="ghost"
          size="icon"
          className="hidden md:inline-flex h-7 w-7"
          onClick={() => setSidebarOpen((v) => !v)}
          title={sidebarOpen ? "Hide sidebar" : "Show sidebar"}
        >
          {sidebarOpen ? (
            <PanelLeftClose className="h-3.5 w-3.5" />
          ) : (
            <PanelLeft className="h-3.5 w-3.5" />
          )}
        </Button>
        <Select value={activeSample} onValueChange={handleSampleChange}>
          <SelectTrigger size="sm" className="text-xs">
            <span data-slot="select-value">
              {samples.find((s) => s.filename === activeSample)?.name ??
                samples[0].name}
            </span>
          </SelectTrigger>
          <SelectContent position="popper">
            {samples.map((s) => (
              <SelectItem key={s.filename} value={s.filename}>
                {s.name}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
        <input
          ref={fileInputRef}
          type="file"
          accept=".json,.jsonc,.json5"
          onChange={(e) => {
            const file = e.target.files?.[0];
            if (file) {
              const reader = new FileReader();
              reader.onload = () => {
                if (typeof reader.result === "string")
                  loadJson(reader.result, file.name);
              };
              reader.readAsText(file);
            }
            e.target.value = "";
          }}
          className="hidden"
        />
        <div className="hidden md:flex items-center gap-2">
          <div className="w-px h-5 bg-border" />
          <Button
            variant="ghost"
            size="icon"
            className="h-7 w-7"
            onClick={() => fileInputRef.current?.click()}
            title="Open file"
          >
            <FolderOpen className="h-3.5 w-3.5" />
          </Button>
          <Button
            variant="ghost"
            size="icon"
            className="h-7 w-7"
            onClick={handlePaste}
            title="Paste JSON"
          >
            <ClipboardPaste className="h-3.5 w-3.5" />
          </Button>
          <Button
            variant="ghost"
            size="icon"
            className="h-7 w-7"
            onClick={handleDownload}
            title="Download"
          >
            <Download className="h-3.5 w-3.5" />
          </Button>
          <Button
            variant="ghost"
            size="icon"
            className="h-7 w-7"
            onClick={handleCopyJson}
            title="Copy JSON"
          >
            <Copy className="h-3.5 w-3.5" />
          </Button>
        </div>
        <ToggleGroup
          type="single"
          value={viewMode}
          onValueChange={(v) => {
            if (v) setViewMode(v as ViewMode);
          }}
          variant="outline"
          size="sm"
          className="ml-auto"
        >
          {VIEW_MODES.map((m) => (
            <ToggleGroupItem key={m.id} value={m.id} className="text-xs px-3">
              {m.label}
            </ToggleGroupItem>
          ))}
        </ToggleGroup>
        <Dialog>
          <DialogTrigger asChild>
            <Button variant="ghost" size="icon" className="h-7 w-7">
              <Settings className="h-3.5 w-3.5" />
            </Button>
          </DialogTrigger>
          <DialogContent className="sm:max-w-sm">
            <DialogHeader>
              <DialogTitle>Settings</DialogTitle>
            </DialogHeader>
            <div className="space-y-4">
              <div>
                <h4 className="text-sm font-medium mb-2">Tree</h4>
                <div className="space-y-2 pl-2">
                  <div className="flex items-center justify-between">
                    <Label htmlFor="tree-values">Values</Label>
                    <Switch
                      id="tree-values"
                      checked={treeShowValues}
                      onCheckedChange={setTreeShowValues}
                    />
                  </div>
                  <div className="flex items-center justify-between">
                    <Label htmlFor="tree-counts">Property counts</Label>
                    <Switch
                      id="tree-counts"
                      checked={treeShowCounts}
                      onCheckedChange={setTreeShowCounts}
                    />
                  </div>
                </div>
              </div>
              <div>
                <h4 className="text-sm font-medium mb-2">Editor</h4>
                <div className="space-y-2 pl-2">
                  <div className="flex items-center justify-between">
                    <Label htmlFor="editor-descriptions">Descriptions</Label>
                    <Switch
                      id="editor-descriptions"
                      checked={editorShowDescriptions}
                      onCheckedChange={setEditorShowDescriptions}
                    />
                  </div>
                  <div className="flex items-center justify-between">
                    <Label htmlFor="editor-counts">Property counts</Label>
                    <Switch
                      id="editor-counts"
                      checked={editorShowCounts}
                      onCheckedChange={setEditorShowCounts}
                    />
                  </div>
                </div>
              </div>
            </div>
          </DialogContent>
        </Dialog>
      </div>

      {/* Editor */}
      <div className="flex-1 min-h-0">
        {viewMode === "raw" ? (
          <div className="flex flex-col h-full bg-background">
            {rawError && (
              <div className="px-3 py-1.5 text-xs bg-red-100 text-red-700 dark:bg-red-950 dark:text-red-400 border-b border-border shrink-0">
                {rawError}
              </div>
            )}
            <textarea
              value={rawText}
              onChange={(e) => handleRawChange(e.target.value)}
              spellCheck={false}
              className="flex-1 w-full bg-transparent text-foreground font-mono text-sm p-4 resize-none outline-none border-none leading-relaxed"
            />
          </div>
        ) : (
          <YamlEditor
            value={yamlValue}
            onChange={setYamlValue}
            schema={schema}
            treeShowValues={treeShowValues}
            treeShowCounts={treeShowCounts}
            editorShowDescriptions={editorShowDescriptions}
            editorShowCounts={editorShowCounts}
            sidebarOpen={sidebarOpen}
            style={
              {
                "--vj-bg": "var(--background)",
                "--vj-bg-panel": "var(--background)",
                "--vj-bg-hover": "var(--accent)",
                "--vj-bg-selected": "var(--primary)",
                "--vj-bg-selected-muted": "var(--accent)",
                "--vj-text-selected": "var(--primary-foreground)",
                "--vj-border": "var(--border)",
                "--vj-border-subtle": "var(--border)",
                "--vj-text": "var(--foreground)",
                "--vj-text-muted": "var(--muted-foreground)",
                "--vj-text-dim": "var(--muted-foreground)",
                "--vj-text-dimmer": "var(--muted-foreground)",
                "--vj-input-bg": "var(--input)",
                "--vj-input-border": "var(--border)",
                "--vj-accent": "var(--primary)",
                "--vj-accent-muted": "var(--accent)",
                "--vj-font": "var(--font-mono)",
              } as React.CSSProperties
            }
          />
        )}
      </div>

      <Dialog open={pasteDialogOpen} onOpenChange={setPasteDialogOpen}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>Paste JSON</DialogTitle>
          </DialogHeader>
          <textarea
            value={pasteText}
            onChange={(e) => setPasteText(e.target.value)}
            placeholder="Paste your JSON here..."
            spellCheck={false}
            className="min-h-[200px] w-full rounded-md border border-input bg-transparent px-3 py-2 text-sm font-mono resize-none outline-none"
          />
          <DialogFooter>
            <DialogClose asChild>
              <Button variant="ghost">Cancel</Button>
            </DialogClose>
            <Button onClick={handlePasteSubmit}>Load</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
